### ISSUE TITLE
Doesnt start...

### ISSUE THREAD

**Issue by danielpmc** [Ankrad/Backup#1]
```root@SERVER01:~/Bots/BackupBot# node server.js
/root/Bots/BackupBot/server.js:26
      .add("backups", "string", {default: "[]"})
       ^

TypeError: Cannot read property 'add' of undefined
    at Object.<anonymous> (/root/Bots/BackupBot/server.js:26:8)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at internal/main/run_main_module.js:21:11
root@SERVER01:~/Bots/BackupBot#
```

**Comment by Ankrad** [comment]
Are you sure you installed [Klasa](https://github.com/dirigeants/klasa)'s master branch?

**Comment by danielpmc** [comment]
Thanks. i didnt have the latest master i was using the npm build. What needs to go into the .env for the bot to work?

**Comment by danielpmc** [comment]
also 
[2019-08-16 15:30:08] Loaded 10 commands.
[2019-08-16 15:30:08] Loaded 9 inhibitors.
[2019-08-16 15:30:08] Loaded 2 finalizers.
[2019-08-16 15:30:08] Loaded 1 monitors.
[2019-08-16 15:30:08] Loaded 1 languages.
[2019-08-16 15:30:08] Loaded 2 providers.
[2019-08-16 15:30:08] Loaded 22 events.
[2019-08-16 15:30:08] Loaded 2 extendables.
[2019-08-16 15:30:08] Loaded 2 tasks.
[2019-08-16 15:30:08] Loaded 57 arguments.
[2019-08-16 15:30:08] Loaded 10 serializers.
[2019-08-16 15:30:08] Uncaught Promise Error:
[2019-08-16 15:30:08] MongoParseError: URI malformed, cannot be parsed
[2019-08-16 15:30:08]     at parseConnectionString (/root/Bots/Backup/node_modules/mongodb/lib/core/uri_parser.js:502:21)
[2019-08-16 15:30:08]     at connect (/root/Bots/Backup/node_modules/mongodb/lib/operations/connect.js:266:3)
[2019-08-16 15:30:08]     at ConnectOperation.execute (/root/Bots/Backup/node_modules/mongodb/lib/operations/connect.js:191:5)
[2019-08-16 15:30:08]     at /root/Bots/Backup/node_modules/mongodb/lib/operations/execute_operation.js:109:26
[2019-08-16 15:30:08]     at new Promise (<anonymous>)
[2019-08-16 15:30:08]     at executeOperation (/root/Bots/Backup/node_modules/mongodb/lib/operations/execute_operation.js:102:10)
[2019-08-16 15:30:08]     at MongoClient.connect (/root/Bots/Backup/node_modules/mongodb/lib/mongo_client.js:216:10)
[2019-08-16 15:30:08]     at Function.MongoClient.connect (/root/Bots/Backup/node_modules/mongodb/lib/mongo_client.js:379:22)
[2019-08-16 15:30:08]     at module.exports.init (/root/Bots/Backup/providers/mongodb.js:13:37)
[2019-08-16 15:30:08]     at Promise.all.map.piece (/root/Bots/Backup/node_modules/klasa/src/lib/structures/base/Store.js:92:62)

**Comment by Ankrad** [comment]
You'll need `MongoDB=YOUR_MONGO_DB_URL` and a `DISCORD_TOKEN=`. I'll add it to the branch.
